name: example
description: A example to demonstrate painter.
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/epnw/painter

dependencies:
  flutter:
    sdk: flutter
  painter:
    path: ../
  flutter_colorpicker: any

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

