name: painter
description: A simple widget to paint with your fingers. Supports setting a background color, undo and export to png!
version: 0.4.0
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/epnw/painter

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.5.0 <3.0.0"